### ISSUE TITLE
Deploying on Heroku

### ISSUE THREAD

**Issue by NicholasWenzel** [NicholasWenzel/internsgopro#11]
Ciao Tom, 

t'es bien retourné en France? Ca fait comment - choque culturelle de retour, ou t'est content d'y être out meme tous les deux?!

J'aimerais bien pusher l'application sur Heroku, mais je n'y arrives pas. J'ai une application error, après avoir suivi le manuel pour pusher sur heroku. T'as une idée ou le problème pourrait être? Je t'envoye le heroku logs. 

Merci, 
Nico

Last login: Mon Feb  6 15:32:29 on ttys002
Nicholass-MacBook-Pro:nofuckingidea nicholaswenzel$ heroku logs
2017-02-06T14:40:45.693156+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
2017-02-06T14:40:45.693187+00:00 app[web.1]: 	from /app/config.ru:in `new'
2017-02-06T14:40:45.693188+00:00 app[web.1]: 	from /app/config.ru:in `<main>'
2017-02-06T14:40:45.693191+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
2017-02-06T14:40:45.693194+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
2017-02-06T14:40:45.693193+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
2017-02-06T14:40:45.693191+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
2017-02-06T14:40:45.693196+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
2017-02-06T14:40:45.693198+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/server.rb:61:in `app'
2017-02-06T14:40:45.693215+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
2017-02-06T14:40:45.693216+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
2017-02-06T14:40:45.693217+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/server.rb:80:in `start'
2017-02-06T14:40:45.693219+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:80:in `block in server'
2017-02-06T14:40:45.693221+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `server'
2017-02-06T14:40:45.693223+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
2017-02-06T14:40:45.693225+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
2017-02-06T14:40:45.693227+00:00 app[web.1]: 	from bin/rails:9:in `require'
2017-02-06T14:40:45.693229+00:00 app[web.1]: 	from bin/rails:9:in `<main>'
2017-02-06T14:40:45.693220+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `tap'
2017-02-06T14:40:45.800238+00:00 heroku[web.1]: Process exited with status 1
2017-02-06T14:40:45.813123+00:00 heroku[web.1]: State changed from starting to crashed
2017-02-06T15:01:45.553399+00:00 heroku[web.1]: State changed from crashed to starting
2017-02-06T15:01:49.390099+00:00 heroku[web.1]: Starting process with command `bin/rails server -p 12518 -e production`
2017-02-06T15:01:54.645421+00:00 app[web.1]: => Booting WEBrick
2017-02-06T15:01:54.645445+00:00 app[web.1]: => Rails 4.2.6 application starting in production on http://0.0.0.0:12518
2017-02-06T15:01:54.645446+00:00 app[web.1]: => Run `rails server -h` for more startup options
2017-02-06T15:01:54.645446+00:00 app[web.1]: => Ctrl-C to shutdown server
2017-02-06T15:01:54.645447+00:00 app[web.1]: Exiting
2017-02-06T15:01:54.645456+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require': /app/app/controllers/places_controller.rb:4: syntax error, unexpected '=', expecting ';' or '\n' (SyntaxError)
2017-02-06T15:01:54.645457+00:00 app[web.1]:   def new = @employer.offers.build
2017-02-06T15:01:54.645457+00:00 app[web.1]:            ^
2017-02-06T15:01:54.645468+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
2017-02-06T15:01:54.645469+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
2017-02-06T15:01:54.645469+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
2017-02-06T15:01:54.645472+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:360:in `require_or_load'
2017-02-06T15:01:54.645472+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:317:in `depend_on'
2017-02-06T15:01:54.645473+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:233:in `require_dependency'
2017-02-06T15:01:54.645473+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
2017-02-06T15:01:54.645474+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:471:in `each'
2017-02-06T15:01:54.645474+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:471:in `block in eager_load!'
2017-02-06T15:01:54.645475+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:469:in `each'
2017-02-06T15:01:54.645475+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:469:in `eager_load!'
2017-02-06T15:01:54.645476+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:346:in `eager_load!'
2017-02-06T15:01:54.645476+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application/finisher.rb:56:in `each'
2017-02-06T15:01:54.645477+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
2017-02-06T15:01:54.645477+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
2017-02-06T15:01:54.645509+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
2017-02-06T15:01:54.645510+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
2017-02-06T15:01:54.645511+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
2017-02-06T15:01:54.645511+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
2017-02-06T15:01:54.645512+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
2017-02-06T15:01:54.645512+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
2017-02-06T15:01:54.645515+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
2017-02-06T15:01:54.645516+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
2017-02-06T15:01:54.645517+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
2017-02-06T15:01:54.645517+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
2017-02-06T15:01:54.645518+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
2017-02-06T15:01:54.645519+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
2017-02-06T15:01:54.645519+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
2017-02-06T15:01:54.645520+00:00 app[web.1]: 	from /app/config/environment.rb:5:in `<top (required)>'
2017-02-06T15:01:54.645520+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
2017-02-06T15:01:54.645521+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
2017-02-06T15:01:54.645521+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
2017-02-06T15:01:54.645523+00:00 app[web.1]: 	from /app/config.ru:3:in `block in <main>'
2017-02-06T15:01:54.645522+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
2017-02-06T15:01:54.645523+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
2017-02-06T15:01:54.645524+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
2017-02-06T15:01:54.645525+00:00 app[web.1]: 	from /app/config.ru:in `new'
2017-02-06T15:01:54.645525+00:00 app[web.1]: 	from /app/config.ru:in `<main>'
2017-02-06T15:01:54.645526+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
2017-02-06T15:01:54.645527+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
2017-02-06T15:01:54.645527+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
2017-02-06T15:01:54.645528+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
2017-02-06T15:01:54.645529+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
2017-02-06T15:01:54.645529+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/server.rb:61:in `app'
2017-02-06T15:01:54.645530+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
2017-02-06T15:01:54.645530+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
2017-02-06T15:01:54.645531+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/server.rb:80:in `start'
2017-02-06T15:01:54.645532+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:80:in `block in server'
2017-02-06T15:01:54.645532+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `tap'
2017-02-06T15:01:54.645533+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `server'
2017-02-06T15:01:54.645534+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
2017-02-06T15:01:54.645535+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
2017-02-06T15:01:54.645535+00:00 app[web.1]: 	from bin/rails:9:in `require'
2017-02-06T15:01:54.645536+00:00 app[web.1]: 	from bin/rails:9:in `<main>'
2017-02-06T15:01:54.802613+00:00 heroku[web.1]: Process exited with status 1
2017-02-06T15:01:54.820215+00:00 heroku[web.1]: State changed from starting to crashed
2017-02-06T15:10:15.306344+00:00 app[api]: Starting process with command `bundle exec rake db:migrate` by user nicholas.wenzel@internsgopro.com
2017-02-06T15:10:23.443970+00:00 heroku[run.4917]: Awaiting client
2017-02-06T15:10:23.471667+00:00 heroku[run.4917]: Starting process with command `bundle exec rake db:migrate`
2017-02-06T15:10:23.677614+00:00 heroku[run.4917]: State changed from starting to up
2017-02-06T15:10:31.085118+00:00 heroku[run.4917]: State changed from up to complete
2017-02-06T15:10:31.070980+00:00 heroku[run.4917]: Process exited with status 0
2017-02-06T15:10:41.319622+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=secret-eyrie-62057.herokuapp.com request_id=27b9dfdd-c3ae-4d4a-a23e-083970dfb2a0 fwd="91.64.24.67" dyno= connect= service= status=503 bytes=
2017-02-06T15:17:46.156855+00:00 app[api]: Starting process with command `bundle exec rake db:migrate` by user nicholas.wenzel@internsgopro.com
2017-02-06T15:17:49.826930+00:00 heroku[run.2250]: Awaiting client
2017-02-06T15:17:49.886854+00:00 heroku[run.2250]: Starting process with command `bundle exec rake db:migrate`
2017-02-06T15:17:50.036383+00:00 heroku[run.2250]: State changed from starting to up
2017-02-06T15:17:57.689407+00:00 heroku[run.2250]: State changed from up to complete
2017-02-06T15:17:57.690499+00:00 heroku[run.2250]: Process exited with status 0
2017-02-06T15:18:51.463026+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=secret-eyrie-62057.herokuapp.com request_id=de55e79d-39f9-4017-974f-61846dc0ff71 fwd="91.64.24.67" dyno= connect= service= status=503 bytes=
Nicholass-MacBook-Pro:nofuckingidea nicholaswenzel$

**Comment by thaume** [comment]
Hello @NicholasWenzel !

Oui choc culturelle, mais très content de rentrer pour attaquer mon nouveau projet de boite :)

Et toi comment vas-tu ? 

Ajoute moi en collaborateur sur Heroku, comme ça je pourrai essayer de résoudre le problème. Je te dirai ensuite ce qui n'allait pas ;)

Cheers!

**Comment by NicholasWenzel** [comment]
Ciao @thaume !

Ah, il faut que tu m'en parle de ton projet de boite! Ca m'intéresse! J'espère que ca à avoir à aider les gens comme moi à mieux gérer la technologie. ;-D

Ici, tout ce passe bien! Je travaille maintenant sur investissement, mais j'avoue que c'est pas si facile de changer de IT à finance du jour au lendemain. En tout cas, je suis bien content d'avoir bien avancé sur Ruby on Rails. D'ailleurs nous avons un jolie nouvel rating system sur l'appli. Tu vas voire, une fois que ca marche sur Heroku. 

Merci pour ton support là-dessus! Je t'ai ajouté comme collaborateur sur Heroku. Bon courage! 

Ciao ciao,
Nico

**Comment by thaume** [comment]
Hello @NicholasWenzel,

Le site est en ligne par ici : https://secret-eyrie-62057.herokuapp.com/

Peux-tu me donner les accès en écriture à ce repo ? Pour que je puisse envoyer mes mises à jour ?

**Comment by NicholasWenzel** [comment]
Déjà fait?! Mais t'es un homme geniale! :-) 

En fait, le repo est sur Github publique: internsgopro_v2. Ca te suffit comme info? Quelle était le problème?

**Comment by thaume** [comment]
@NicholasWenzel il faut que tu m'ajoutes dans la liste des collaborateurs (sur le repo : settings > collaborators)

Je te montrerai le problème sur le commit ;)

**Comment by NicholasWenzel** [comment]
Je viens de t'ajouter! Nous avons un developper qui est en train de terminer le coding pour le design du rating form. Il va y avoir un nouveau push de sa part sur Github. Il faut qu'on s'assure que le problème sur Heroku ne survienne en ce cas. 

Très curieux de voir la raison pour le problème dans heroku!  ;-)

**Comment by thaume** [comment]
Ok super :)

C'était assez simple en fait : 
- https://github.com/NicholasWenzel/internsgopro_v2/commit/eb879783ba5fc711d219e65bc7a341e0eb5ed3c4 => certainement une faute de frappe de ta part
- https://github.com/NicholasWenzel/internsgopro_v2/commit/7cbfeef2dbe780712371df10841a19d5b6ce25e6 => il manquait un keyword "end" à la fin de ton controller

Cheers !

**Comment by NicholasWenzel** [comment]
C'est tout!? Haha, il m'aura fallut des heures pour arriver à comprendre que c'était la raison. ;-D

Comment t'as fait pour comprendre ca? Je demande pour arriver à résoudre ces problèmes tout seule en futur.

**Comment by thaume** [comment]
Dans tes logs il y a écris à un moment :

```
/app/app/controllers/places_controller.rb:4: syntax error, unexpected '=', expecting ';' or '\n' (SyntaxError)
2017-02-06T15:01:54.645457+00:00 app[web.1]: def new = @employer.offers.build
2017-02-06T15:01:54.645457+00:00 app[web.1]: ^
2017-02-06T15:01:54.645468+00:00 app[web.1]: from 
```

Ce qui veut dire qu'il y a un problème au niveau du `=` à la ligne `def new = @employer.offers.build`. C'est alors évident qu'il y a un problème :)

Une fois cette erreur résolue, l'erreur du `end` est apparue de la même manière !

**Comment by NicholasWenzel** [comment]
Top Tom!
